server:
  port: 3000

mybatis:
  type-aliases-package: com.example.demo.model
  mapper-locations: classpath:mapper/*.xml

spring:
  #配置热部署
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  datasource:
    #基本属性
    url: jdbc:postgresql://localhost:5432/tutorial?useSSL=false
    username: postgres
    password: cxb123456
    driver-class-name: org.postgresql.Driver
    #增加druid 配置
    type: com.alibaba.druid.pool.DruidDataSource
    # // http://localhost:3000/druid/index.html
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: : druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true


